version: '3.7'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: holdwell_test
      MYSQL_USER: myuser
      MYSQL_PASSWORD: holdwell527
    ports:
      - "3307:3306"
    volumes:
      - mysql_datas:/var/lib/mysql
      - /databackup:/backup

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"

  nodejs:
    build: ./nodejs
    container_name: nodejs_container
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: myuser
      DB_PASSWORD: holdwell527
      DB_NAME: holdwell_test
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    command: ["./wait-for-it.sh", "mysql:3306", "--", "node", "myservice.js"]

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./vue_web/dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  mysql_datas:
